# Generated by Django 3.2.13 on 2022-11-24 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_path', models.CharField(max_length=1000)),
                ('provider_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('overview', models.TextField(null=True)),
                ('adult', models.BooleanField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('poster_path', models.CharField(max_length=200, null=True)),
                ('backdrop_path', models.CharField(max_length=300, null=True)),
                ('youtube_key', models.CharField(max_length=100, null=True)),
                ('actors', models.ManyToManyField(related_name='actors_movie', to='movies.Actor')),
                ('genres', models.ManyToManyField(related_name='genres_movie', to='movies.Genre')),
                ('is_watched', models.ManyToManyField(related_name='watched_movie', to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(related_name='keywords_movie', to='movies.Keyword')),
                ('like_users', models.ManyToManyField(related_name='like_movie', to=settings.AUTH_USER_MODEL)),
                ('providers', models.ManyToManyField(related_name='provider_movie', to='movies.Provider')),
                ('wish_watch', models.ManyToManyField(related_name='wish_movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('check_movie', models.ManyToManyField(to='movies.Movie')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('check_movie', models.ManyToManyField(to='movies.Movie')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actorcharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1000)),
                ('actor', models.ManyToManyField(to='movies.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Actorasknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asknown', models.CharField(max_length=1000)),
                ('actor', models.ManyToManyField(to='movies.Actor')),
            ],
        ),
    ]
